Add thread-local log level
ruby/logger pull request #85
Opened 2023-01-15 16:32 UTC by mperham

This adds Logger#with_level which provides a thread-local log level so Threads can temporarily enable logging for a given block.

```ruby
log = Logger.new
log.level = :info

Thread.new do
  log.with_level(:debug) do
    log.debug("Will log")
  end
end.join

log.debug("Won't log")
```

Fixes #84

2023-02-06 22:48 UTC, mperham commented on lib/logger.rb
> +  def with_level(severity, &block)
Alternative name: `at`?

```ruby
log.at(:debug) do
  log.debug("You'll see this")
end
```

2023-02-07 00:44 UTC, ioquatix commented
Sorry, I did not see this. Please mention me or add me as a reviewer in the future, otherwise I don't know about it :)

2023-02-07 00:45 UTC, ioquatix commented on lib/logger.rb
> +  def with_level(severity, &block)
I think `with_level` is much more clear what is going on.

2023-02-09 02:41 UTC, ioquatix approved these changes
LGTM.

2023-02-09 02:59 UTC, jeremyevans requested changes
I'm OK with the idea, but I'm against pollute `Thread.current` with this.  Instead, add a instance variable storing a hash inside the logger keyed by `Thread.current`.  This approach also makes it simple to change from a thread-local implementation to a fiber-local or global implementation by changing the key.

2023-02-09 02:59 UTC, jeremyevans commented on lib/logger/severity.rb
> +          UNKNOWN
Since you are moving this anyway, can you switch from a case statement to a hash lookup?

2023-02-09 02:59 UTC, jeremyevans commented on lib/logger.rb
> +  def with_level(severity, &block)
`&block` is not needed, since you are only yielding and not capturing.

2023-02-09 03:33 UTC, ioquatix commented
Thanks @jeremyevans, great review.

2023-02-09 17:06 UTC, mperham commented
Ok, refactored based on feedback.

2023-02-09 23:47 UTC, jeremyevans requested changes
Looks pretty good.  One more implementation change requested.

2023-02-09 23:47 UTC, jeremyevans commented on lib/logger.rb
> +    @tll = ObjectSpace::WeakMap.new # thread-local levels
I think it would be best to use a plain hash instead of a WeakMap.  You can have the `ensure` block delete from `@tll` if there was no key set originally, then you shouldn't need the WeakMap.

2023-02-10 00:30 UTC, ioquatix requested changes

2023-02-10 00:30 UTC, ioquatix commented on lib/logger/severity.rb
> +        LEVELS[k] || raise(ArgumentError, "invalid log level: #{severity}")
```suggestion
        key = severity.to_s.downcase
        LEVELS[key] || raise(ArgumentError, "invalid log level: #{severity}")
```

2023-02-10 00:30 UTC, ioquatix commented on lib/logger.rb
> +    @tll[Thread.current] || @level
Using `Thread.current` as a key is different from using `Thread.current[key]` as the former is per-thread and the latter is per-fiber.

```suggestion
    @level_override[Fiber.current] || @level
```

I also don't like `@tll` as it's not clear what that means. I'd call it what it is, "level_override" or something like that.

2023-02-10 00:40 UTC, jeremyevans commented on lib/logger.rb
> +    @tll[Thread.current] || @level
thread local level was my guess, but I agree a more clear name would be optimal.  However, that change could be made later.

Ideally there would be a method returning the key to use, so you could easily subclass and override to get Fiber-local, Thread-local, or global behavior.  I don't have a problem defaulting to Fiber-local.

2023-02-10 00:44 UTC, ioquatix commented on lib/logger.rb
> +    @tll[Thread.current] || @level
I'm personally okay with not having a public interface for this yet, as I want to propose some further changes as you suggested. I think if we can start with fiber local, it's good, and we can later expand that. It should be good enough for @mperham use case (equivalent to what's currently in Sidekiq).

2023-02-10 00:53 UTC, ioquatix approved these changes

2023-02-10 00:54 UTC, ioquatix commented
Sorry, one more change is required, we will need to add `require 'fiber'` for `Fiber.current` to work.

2023-02-10 00:57 UTC, jeremyevans approved these changes
Couple of small things that could be fixed, but I don't think need to block merging.

2023-02-10 00:57 UTC, jeremyevans commented on CHANGELOG.md
> +* Add thread-local log levels using `Logger#with_level` [#84](https://github.com/ruby/logger/issue/84)
Currently, these are fiber-local.

2023-02-10 00:57 UTC, jeremyevans commented on test/logger/test_severity.rb
> +        Thread.new do
This tests for Thread-local, not explicitly for Fiber-local, but works since a new Thread is also a new Fiber.  Not sure if we want to explicitly test for Fiber-localness.  Could be done later.

2023-02-10 00:58 UTC, mperham commented
> Sorry, one more change is required, we will need to add `require 'fiber'` for `Fiber.current` to work.

Really? irb 3.2 works fine without it:

```
% irb
> Fiber.current
=> #<Fiber:0x00000001051c8698 (resumed)>
```

2023-02-10 00:58 UTC, jeremyevans commented
According to CI, `logger` supports Ruby 2.5+ (gem says Ruby 2.3+).

2023-02-10 01:00 UTC, mperham commented
> According to CI, `logger` supports Ruby 2.5+ (gem says Ruby 2.3+).

Right, looks like 3.1+ doesn't require "fiber" anymore.

2023-02-10 01:08 UTC, merged

2023-02-10 04:04 UTC, ioquatix commented
Thanks @mperham - I want to make one more PR and then we will try to cut a release.

2023-02-14 12:04 UTC, yahonda commented
This commit introduces `NoMethodError: undefined method `[]' for nil:NilClass`
reported at https://github.com/resque/resque/issues/1856

2023-07-09 16:25 UTC, jaynetics commented
> This commit introduces NoMethodError: undefined method []' for nil:NilClass`
> reported at https://github.com/resque/resque/issues/1856

Generally speaking, this breaks any logger subclass that does not call super in its initializer. `jekyll` is another gem affected by this on Ruby 3.3, and there might be more. @ioquatix i wonder whether avoiding this breaking change might be worth a little amendment, like extracting `@level_override` into `def level_override; @level_override ||= {} end` or so?

2023-07-09 17:04 UTC, mperham commented
I don't believe adding additional complexity to work around 3rd party bugs is a good idea. Not calling super is a bug, no?

2023-09-25 02:13 UTC, skipkayhil commented
> I want to make one more PR and then we will try to cut a release.

Hey @ioquatix, did that other PR ever land? I'd love to see this released so we could potentially use it to replace the `LoggerThreadSafeLevel` patch in Rails

2024-06-10 23:40 UTC, ghiculescu commented
@skipkayhil FYI this has been released now.

2024-11-06 22:24 UTC, skipkayhil commented
https://github.com/ruby/logger/pull/103

I believe we need something like this to replace `log_at` in Active Support. I think this idea was discussed some above so hopefully this is what everyone was thinking